apiVersion: apps/v1
kind: Deployment
metadata:
  name: super-api
spec:
  selector:
    matchLabels:
      app: super-api
  template:
    metadata:
      labels:
        app: super-api
    spec:
      volumes:
        - name: config
          configMap:
            name: super-api-cm
            items:
              - key: configfile
                path: config.toml
      containers:
      - name: super-api
        image: ghcr.io/gbaeke/super:1.0.3
        env:
          - name: PORT
            value: "9090"
          - name: IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: RANDOMFIELD
            valueFrom:
              configMapKeyRef:
                name: super-api-cm
                key: randomfield
        args:
          - "--welcome='Hello from AKS on IP $(IP). Extra data from CM: $(RANDOMFIELD)"
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 9090
        volumeMounts:
          - name: config
            mountPath: /config
