kind: Service
apiVersion: v1
metadata:
  name:  go-template-load
spec:
  selector:
    app:  go-template-load
  type:  ClusterIP
  ports:
  - name:  http
    port:  80
    targetPort:  8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-template-load
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-template-load
  template:
    metadata:
      labels:
        app: go-template-load
    spec:
      containers:
      - name: go-template-load
        image: gbaeke/go-template:load
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 8080
