apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-template-load
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 10