apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-template
  labels:
    app: go-template
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-template
  template:
    metadata:
      labels:
        app: go-template
    spec:
      containers:
        - name: go-template
          image: ghcr.io/gbaeke/go-template:0.0.2
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 64Mi