apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: web
    tier: frontend
  annotations:
    owner: gbaeke
spec:
  containers:
  - name: web
    image: nginx
    imagePullPolicy: Always
    ports:
    - containerPort: 80
      protocol: TCP
      name: web
    # limits and requests are equal - QoS class = guaranteed
    # eviction happens in this order: BestEffort, Burstable, Guaranteed
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 100m
        memory: 64Mi
    livenessProbe:
      httpGet:
        path: /
        port: web
      initialDelaySeconds: 30
      timeoutSeconds: 1
      failureThreshold: 3
  restartPolicy: Always
  terminationGracePeriodSeconds: 60