apiVersion: v1
kind: Pod
metadata:
    name: nginx
    labels:
        app: nginx
    namespace: test
spec:
    containers:
    - name: nginx
        image:  nginx
        ports:
        - containerPort: 80
        protocol: TCP
    restartPolicy: Always