apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-load
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keda-load
  template:
    metadata:
      labels:
        app: keda-load
    spec:
      containers:
      - name: keda-load
        image: gbaeke/go-template:load
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 8080
