apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: superapi-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: app.20.76.129.250.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: superapi
            port:
              number: 80