apiVersion: apps/v1
kind: Deployment
metadata:
  name: super-api
  labels:
    app: super-api
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 3
  selector:
    matchLabels:
      app: super-api
  template:
    metadata:
      labels:
        app: super-api
    spec:
      containers:
        - name: super-api
          image: ghcr.io/gbaeke/super:1.0.3
          args:
            - "--log=true"
            - "--port=8080"
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 64Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3



