apiVersion: apps/v1
kind: Deployment
metadata:
  name: super-api
  labels:
    app: super-api
spec:
  strategy:
    type: Recreate
  replicas: 3
  selector:
    matchLabels:
      app: super-api
  template:
    metadata:
      labels:
        app: super-api
        tier: backend
    spec:
      containers:
        - name: super-api
          image: ghcr.io/gbaeke/super:1.0.3
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 64Mi