apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: smi
  labels:
    name: debug
  annotations:
    linkerd.io/inject: enabled
spec:
  containers:
  - name: debug
    image: praqma/network-multitool:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
