apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: superapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: superapi
  template:
    metadata:
      labels:
        app: superapi
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: superapi
        image: ghcr.io/gbaeke/super:1.0.3
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "50m"
        env:
          - name: WELCOME
            valueFrom:
              configMapKeyRef:
                name: superapi-config
                key: WELCOME
        ports:
        - containerPort: 8080
  strategy:
    canary:
      canaryService: superapi-canary
      stableService: superapi-stable
      trafficRouting:
        smi:
          rootService: superapi-svc
          trafficSplitName: superapi-split
      steps:
      - setWeight: 10
      - pause: {}