apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      volumes:
        - name: webapp
          emptyDir:
            medium: Memory
      initContainers:
        - name: configure
          image: alpine/git
          volumeMounts:
            - name: webapp
              mountPath: /work
          command:
            - git
            - clone
            - https://github.com/gbaeke/static-web.git
            - '/work'
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: webapp
              mountPath: /usr/share/nginx/html            
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi